# Documentation BUILD file

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_docs",
    srcs = ["iso26262_guide.md"],
)

filegroup(
    name = "iso26262_guide",
    srcs = ["iso26262_guide.md"],
)

